name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

#defaults:
#  run:
#    working-directory: ./CMR/python #if more projects are added, then remove this
jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.3
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Unit Tests
        run: python3 -m unittest discover
        working-directory: ./CMR/python
